title: My Blog
author: Solomon Zhang
theme: minima
email: szhang008@citymail.cuny.edu
description: > # this means to ignore newlines until "baseurl:"
  This is my blog and I will update it daily.

# social links
twitter_username: N/A # DO NOT include the @ character, or else the build will fail!
github_username: szhang008CCNY # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
